// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFXoanH44h_beo2iUW5Pkd1k0GyphMac',
    appId: '1:386578870961:web:776fcfed1a138dccc3e890',
    messagingSenderId: '386578870961',
    projectId: 'learnfirebaseflutter-efbcb',
    authDomain: 'learnfirebaseflutter-efbcb.firebaseapp.com',
    storageBucket: 'learnfirebaseflutter-efbcb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVAGNnRI1QCRTWXTAuG7v1utJyvhz8Cwg',
    appId: '1:386578870961:android:989ff8db75466fd2c3e890',
    messagingSenderId: '386578870961',
    projectId: 'learnfirebaseflutter-efbcb',
    storageBucket: 'learnfirebaseflutter-efbcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLmsgGfOL_Iyh7S6LxzqQpptJHzNZGkM',
    appId: '1:386578870961:ios:a51c8a5f255d1d46c3e890',
    messagingSenderId: '386578870961',
    projectId: 'learnfirebaseflutter-efbcb',
    storageBucket: 'learnfirebaseflutter-efbcb.firebasestorage.app',
    iosBundleId: 'com.example.learnFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRLmsgGfOL_Iyh7S6LxzqQpptJHzNZGkM',
    appId: '1:386578870961:ios:a51c8a5f255d1d46c3e890',
    messagingSenderId: '386578870961',
    projectId: 'learnfirebaseflutter-efbcb',
    storageBucket: 'learnfirebaseflutter-efbcb.firebasestorage.app',
    iosBundleId: 'com.example.learnFirebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMFXoanH44h_beo2iUW5Pkd1k0GyphMac',
    appId: '1:386578870961:web:73bf6852ca4531bfc3e890',
    messagingSenderId: '386578870961',
    projectId: 'learnfirebaseflutter-efbcb',
    authDomain: 'learnfirebaseflutter-efbcb.firebaseapp.com',
    storageBucket: 'learnfirebaseflutter-efbcb.firebasestorage.app',
  );
}
